### ISSUE TITLE
Add a Contributing.md file

### ISSUE THREAD

**Issue by Dhavisco** [HackSocNotts/hacksocnotts.github.io#213]
### What is this issue about?

This issue is about adding a `CONTRIBUTING.md` file to the repository. A `CONTRIBUTING.md` file serves as a guide for contributors to understand how they can contribute to the project, including the guidelines, best practices, and steps to follow.

### Why is this issue important?

- A `CONTRIBUTING.md` file provides clear instructions for potential contributors, making it easier for them to participate in the project.
- It helps maintain consistency in the contribution process and ensures that contributions align with the project's goals.
- By including guidelines and best practices, it improves the overall quality of contributions.

### What needs to be done?

- Create a `CONTRIBUTING.md` file in the root directory of the repository.
- Populate the file with guidelines, such as how to report issues, how to propose changes, and the coding style to follow.
- Include information on how to set up a development environment, run tests, and submit pull requests.

**Comment by UnicornsOnLSD** [comment]
This page is largely maintained internally by HackSoc, members can reach us via Discord if they have any questions. It looks like there was a `CONTRIBUTING.md` pre-redesign, but this has been lost (but is still referenced in the readme).
