### ISSUE TITLE
Calendar doesn't show historic events

### ISSUE THREAD

**Issue by erinosher** [HackSocNotts/hacksocnotts.github.io#6]
Because of the way I've loaded events into Redux, the calendar doesn't show historical events.

What should happen is that all of the events are loaded into redux, and then the next ten events should also be loaded into another piece of state to be used on the events page.

The events are loaded in `src/services/eventsService.jsx` and then the reducer for events is in `src/store/reducers/eventsReducer.jsx`

**Comment by shad-k** [comment]
@aaronosher hi, I'd like to take this up if it's fine.

Also, do you think dispatching two actions would solve this problem? Just thinking off the top of my head.

**Comment by erinosher** [comment]
Hi @shad-k that'd be great. I am confident that'd probably work.

Do take a look at how the events, event, and calendar pages are preventing errors while waiting for the LOAD_EVENTS_SUCCESS action to dispatch. If you go with that approach, it's probably just a case of adding a second loader and modifying the data source for the calendar or events page.

**Comment by shad-k** [comment]
@aaronosher
After going through the code I see that we can conditionally render the events according to the date. How does that sound?
Basically, events store will have all the events and the Events.jsx shall conditionally render events based on whether it's date lies after the current date.
