### ISSUE TITLE
Make Footer Stick to Bottom

### ISSUE THREAD

**Issue by erinosher** [HackSocNotts/hacksocnotts.github.io#89]
On small pages, the footer goes above the bottom of the page.

![Footer in middle of page](https://image.prntscr.com/image/hWJUsv9lTtmZMpKWsIKsMg.png)

It should stay at the bottom of the page, but also not be `fixed` allowing it to be beneath the bottom of the page, as seen below.

![footer below bottom of page](https://i.imgur.com/jtUe02e.jpg)

**Comment by liorbentov** [comment]
I would like to solve it

**Comment by DanielCordell** [comment]
@liorbentov Go for it! ✊

**Comment by BadrChoubai** [comment]
I'd love to help on this issue

**Comment by catherine-o** [comment]
I will work on this issue!

**Comment by catherine-o** [comment]
Created a pull request :) Happy Hacktoberfest

**Comment by erinosher** [comment]
Resolved by @GeovanniG in #97
