### ISSUE TITLE
Use a better Markdown Compiler

### ISSUE THREAD

**Issue by DanielCordell** [HackSocNotts/hacksocnotts.github.io#94]

**Comment by Emersont1** [comment]
I've been using https://github.com/drdrang/php-markdown-extra-math for a while on my website and it works pretty good, and has LaTeX support

**Comment by erinosher** [comment]
> I've been using https://github.com/drdrang/php-markdown-extra-math for a while on my website and it works pretty good, and has LaTeX support

@Emersont1 it looks fairly good, however, the website is written in JavaScript, so I'm afraid it's not a viable solution.

**Comment by Emersont1** [comment]
okay no problem, i assumed it was php

**Comment by Emersont1** [comment]
No longer relevant with new Hugo site
